[package]
name = "unnamed"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
winit = "0.26.1"
ash = "0.37.0"
ash-window = "0.10.0"
shaderc = "0.8.0"
